"""
GitHub Tools — post comments and update PR status.
Agents use these to report findings back to GitHub PRs.
"""
from __future__ import annotations

import json
import os

import boto3
import httpx
import structlog
from strands import tool

logger = structlog.get_logger(__name__)


def _get_installation_token(repo_full_name: str) -> str:
    """Gets GitHub App installation token from Secrets Manager + GitHub API."""
    secret_arn = os.environ.get("GITHUB_SECRET_ARN")
    if not secret_arn:
        raise RuntimeError("GITHUB_SECRET_ARN not set")

    sm = boto3.client("secretsmanager", region_name=os.environ.get("AWS_REGION", "ap-northeast-2"))
    creds = json.loads(sm.get_secret_value(SecretId=secret_arn)["SecretString"])

    from github_auth import create_installation_token  # type: ignore[import]
    return create_installation_token(
        app_id=creds["appId"],
        private_key=creds["privateKey"],
        installation_id=creds["installationId"],
    )


def _github_request(method: str, url: str, token: str, **kwargs) -> dict:
    resp = httpx.request(
        method,
        url,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        timeout=15,
        **kwargs,
    )
    resp.raise_for_status()
    return resp.json() if resp.content else {}


@tool
def post_pr_comment(
    repo_full_name: str,
    pr_number: int,
    risk_level: str,
    merge_recommendation: str,
    summary: str,
    findings_by_severity: dict[str, int],
    report_id: str,
) -> str:
    """
    Posts an analysis summary comment on a GitHub Pull Request.

    Args:
        repo_full_name: Repository in owner/repo format
        pr_number: Pull Request number
        risk_level: CRITICAL | HIGH | MEDIUM | LOW
        merge_recommendation: APPROVE | REQUEST_CHANGES | BLOCK
        summary: Human-readable analysis summary
        findings_by_severity: Dict of severity → count
        report_id: Report ID for dashboard link

    Returns:
        URL of the created comment
    """
    token = _get_installation_token(repo_full_name)

    risk_emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(risk_level, "⚪")
    rec_emoji = {"APPROVE": "✅", "REQUEST_CHANGES": "⚠️", "BLOCK": "🚫"}.get(merge_recommendation, "❓")
    dashboard_url = os.environ.get("DASHBOARD_URL", "https://app.agentops.example.com")

    total_critical = findings_by_severity.get("CRITICAL", 0)
    total_high = findings_by_severity.get("HIGH", 0)
    total_medium = findings_by_severity.get("MEDIUM", 0)
    total_low = findings_by_severity.get("LOW", 0)
    total_info = findings_by_severity.get("INFO", 0)

    body = f"""## {risk_emoji} AgentOps Analysis Report

**Risk Level:** {risk_emoji} `{risk_level}`
**Recommendation:** {rec_emoji} `{merge_recommendation}`

### Summary
{summary}

### Findings
| Severity | Count |
|----------|-------|
| 🔴 Critical | {total_critical} |
| 🟠 High | {total_high} |
| 🟡 Medium | {total_medium} |
| 🟢 Low | {total_low} |
| ℹ️ Info | {total_info} |

### Actions
- [📊 View Full Report]({dashboard_url}/reports/{report_id})
- To approve: `/approve {report_id}`
- To request fix: `/fix {report_id}`

---
*Generated by [AgentOps Platform](https://github.com/your-org/aigo) • Powered by Claude Sonnet*
"""

    result = _github_request(
        "POST",
        f"https://api.github.com/repos/{repo_full_name}/issues/{pr_number}/comments",
        token,
        json={"body": body},
    )

    comment_url = result.get("html_url", "")
    logger.info("PR comment posted", repo=repo_full_name, pr_number=pr_number, url=comment_url)
    return comment_url


@tool
def set_commit_status(
    repo_full_name: str,
    commit_sha: str,
    state: str,
    description: str,
    context: str = "AgentOps/analysis",
) -> str:
    """
    Sets a commit status check on GitHub.

    Args:
        repo_full_name: Repository in owner/repo format
        commit_sha: Git commit SHA
        state: pending | success | failure | error
        description: Short status description (max 140 chars)
        context: Status context identifier

    Returns:
        Confirmation string
    """
    token = _get_installation_token(repo_full_name)
    _github_request(
        "POST",
        f"https://api.github.com/repos/{repo_full_name}/statuses/{commit_sha}",
        token,
        json={"state": state, "description": description[:140], "context": context},
    )
    logger.info("Commit status set", repo=repo_full_name, sha=commit_sha[:8], state=state)
    return f"Commit status set to {state}"
