"""
Patch Tools — save and validate code patches generated by the Fix Agent.
"""
from __future__ import annotations

import os
import re
import subprocess
import tempfile
from pathlib import Path

import boto3
import structlog
from strands import tool

logger = structlog.get_logger(__name__)


def _s3() -> boto3.client:
    return boto3.client("s3", region_name=os.environ.get("AWS_REGION", "ap-northeast-2"))


def _patches_bucket() -> str:
    v = os.environ.get("S3_PATCHES_BUCKET")
    if not v:
        raise RuntimeError("S3_PATCHES_BUCKET not set")
    return v


@tool
def validate_patch_syntax(patch_content: str) -> str:
    """
    Validates that a patch string is syntactically valid unified diff format.

    Args:
        patch_content: The unified diff content to validate

    Returns:
        "VALID" if the patch syntax is correct, or an error description
    """
    with tempfile.NamedTemporaryFile(mode="w", suffix=".diff", delete=False) as f:
        f.write(patch_content)
        tmp_path = f.name

    try:
        with tempfile.TemporaryDirectory() as repo_dir:
            # Init a temp git repo to test patch
            subprocess.run(["git", "init"], cwd=repo_dir, check=True, capture_output=True, timeout=10)
            subprocess.run(["git", "config", "user.email", "test@test.com"], cwd=repo_dir, check=True, capture_output=True)
            subprocess.run(["git", "config", "user.name", "Test"], cwd=repo_dir, check=True, capture_output=True)

            # Create stub files mentioned in the patch
            for match in re.finditer(r"^--- a/(.+)$", patch_content, re.MULTILINE):
                file_path = Path(repo_dir) / match.group(1)
                file_path.parent.mkdir(parents=True, exist_ok=True)
                file_path.touch()

            result = subprocess.run(
                ["git", "apply", "--check", tmp_path],
                cwd=repo_dir,
                capture_output=True,
                text=True,
                timeout=15,
            )

            if result.returncode == 0:
                return "VALID"
            return f"INVALID: {result.stderr.strip()}"
    except Exception as e:
        return f"VALIDATION_ERROR: {e}"
    finally:
        Path(tmp_path).unlink(missing_ok=True)


@tool
def save_patch(
    fix_id: str,
    org_id: str,
    repo_id: str,
    patch_content: str,
    patch_description: str,
) -> str:
    """
    Saves a validated patch to S3 and returns the S3 key.

    Args:
        fix_id: Fix request ID
        org_id: Organization ID
        repo_id: Repository ID
        patch_content: The unified diff content
        patch_description: Human-readable description of what this patch fixes

    Returns:
        S3 key of the saved patch, or an error string
    """
    validation = validate_patch_syntax(patch_content)
    if validation != "VALID":
        logger.error("Invalid patch syntax", fix_id=fix_id, validation=validation)
        return f"ERROR: Patch validation failed — {validation}"

    s3_key = f"patches/{org_id}/{repo_id}/{fix_id}/fix.diff"
    metadata_key = f"patches/{org_id}/{repo_id}/{fix_id}/metadata.json"

    import json
    from datetime import datetime, timezone

    _s3().put_object(
        Bucket=_patches_bucket(),
        Key=s3_key,
        Body=patch_content.encode("utf-8"),
        ContentType="text/plain",
        ServerSideEncryption="aws:kms",
        Metadata={"fix_id": fix_id, "org_id": org_id, "repo_id": repo_id},
    )

    _s3().put_object(
        Bucket=_patches_bucket(),
        Key=metadata_key,
        Body=json.dumps({
            "fixId": fix_id,
            "orgId": org_id,
            "repoId": repo_id,
            "description": patch_description,
            "patchS3Key": s3_key,
            "createdAt": datetime.now(timezone.utc).isoformat(),
        }).encode("utf-8"),
        ContentType="application/json",
        ServerSideEncryption="aws:kms",
    )

    logger.info("Patch saved", fix_id=fix_id, s3_key=s3_key, size=len(patch_content))
    return s3_key


@tool
def list_patches_for_fix(fix_id: str, org_id: str, repo_id: str) -> str:
    """
    Lists all patches stored for a given fix request.

    Args:
        fix_id: Fix request ID
        org_id: Organization ID
        repo_id: Repository ID

    Returns:
        JSON string with list of patch S3 keys
    """
    import json
    prefix = f"patches/{org_id}/{repo_id}/{fix_id}/"
    response = _s3().list_objects_v2(Bucket=_patches_bucket(), Prefix=prefix)
    keys = [obj["Key"] for obj in response.get("Contents", []) if obj["Key"].endswith(".diff")]
    return json.dumps({"fix_id": fix_id, "patches": keys})
